/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Calendar as PrismaCalendar } from "@prisma/client";

export class CalendarServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.CalendarCountArgs, "select">): Promise<number> {
    return this.prisma.calendar.count(args);
  }

  async calendars<T extends Prisma.CalendarFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CalendarFindManyArgs>
  ): Promise<PrismaCalendar[]> {
    return this.prisma.calendar.findMany<Prisma.CalendarFindManyArgs>(args);
  }
  async calendar<T extends Prisma.CalendarFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CalendarFindUniqueArgs>
  ): Promise<PrismaCalendar | null> {
    return this.prisma.calendar.findUnique(args);
  }
  async createCalendar<T extends Prisma.CalendarCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CalendarCreateArgs>
  ): Promise<PrismaCalendar> {
    return this.prisma.calendar.create<T>(args);
  }
  async updateCalendar<T extends Prisma.CalendarUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CalendarUpdateArgs>
  ): Promise<PrismaCalendar> {
    return this.prisma.calendar.update<T>(args);
  }
  async deleteCalendar<T extends Prisma.CalendarDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.CalendarDeleteArgs>
  ): Promise<PrismaCalendar> {
    return this.prisma.calendar.delete(args);
  }
}
